#!/usr/bin/env python3
"""
LLM Audit Response Analysis Agent
Iterates through every entry in data/entries.json, sends each response to a
local Ollama model, and progressively builds an analysis in data/analysis/.

Each entry's accumulated insights are passed as context to Ollama before the
next entry is processed, so the model refines the analysis iteratively.

Usage:
    python analyze_responses.py                   # default model (llama3.2)
    python analyze_responses.py --model mistral
    python analyze_responses.py --fresh           # wipe previous analysis
    python analyze_responses.py --skip-wordcloud

Requirements:
    pip install requests wordcloud matplotlib
"""

import argparse
import json
import re
import sys
import time
from collections import Counter
from pathlib import Path

import requests

try:
    from wordcloud import WordCloud
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors
    HAS_WC = True
except ImportError:
    HAS_WC = False

# ── Paths ──────────────────────────────────────────────────────────────────────
ROOT    = Path(__file__).parent
DATA    = ROOT / "data"
OUT     = DATA / "analysis"
ENTRIES = DATA / "entries.json"

# ── Config ─────────────────────────────────────────────────────────────────────
OLLAMA_BASE    = "http://localhost:11434"
DEFAULT_MODEL  = "llama3.2"
MAX_RESP_CHARS = 8000   # truncate very long responses to keep prompts manageable
TIMEOUT_S      = 240    # seconds to wait for Ollama

PROFILE_LABELS = {
    "A":  "Career Changer (non-technical background)",
    "B":  "Working Professional (employed full-time)",
    "C":  "International Student",
    "D":  "Undergrad → Grad (applying straight from bachelor's)",
    "D1": "CU Boulder Undergrad (considering staying for MS)",
}

# ── Stopwords for word cloud ───────────────────────────────────────────────────
STOPWORDS = set("""
a about above after all also although an and another any are aren as at back be
because been before being below between both but by came can cannot come could
did didn do does don down during each either else even ever every few find for
from get give good great had has have he her here him his how however i if in
into is it its just know like ll look make many may me might more most much my
need no nor not now of often on one only or other our out over own per rather re
s same see seem she should since so some still such t than that the their them
then there therefore these they this those though through thus to too try until
us use ve very was we were what when where whether which while who will with
within would yet you your
""".split())

# ── Empty analysis skeleton ────────────────────────────────────────────────────
EMPTY_ANALYSIS = {
    "sites":        [],
    "themes":       [],
    "improvements": {"P1": [], "P2": [], "P3": []},
    "good_feedback": [],
    "bad_feedback":  [],
    "insights":      [],
    "processed_ids": [],
    "entry_count":   0,
}

# ── JSON schema handed to Ollama ───────────────────────────────────────────────
SCHEMA = """{
  "sites": [
    {
      "url": "exact URL or domain name found in the response",
      "frequency": <integer — how many times seen so far across all entries>,
      "context": "what this source was cited for"
    }
  ],
  "themes": [
    {
      "theme": "short theme name (≤6 words)",
      "frequency": <integer>,
      "description": "what this theme represents across responses"
    }
  ],
  "improvements": {
    "P1": [{"issue": "...", "rationale": "why this critically harms CU Boulder's representation"}],
    "P2": [{"issue": "...", "rationale": "significant gap but not blocking"}],
    "P3": [{"issue": "...", "rationale": "minor improvement"}]
  },
  "good_feedback":  [{"point": "positive thing said about CU Boulder", "frequency": <integer>}],
  "bad_feedback":   [{"point": "negative or missing thing about CU Boulder", "frequency": <integer>}],
  "insights": [
    {
      "insight": "non-obvious finding worth noting",
      "importance": "high | medium | low",
      "category": "visibility | accuracy | competitor | content_gap | sentiment | other"
    }
  ],
  "processed_ids": [<list of integer entry IDs already processed, INCLUDING the current one>],
  "entry_count": <total entries processed so far including the current one>
}"""

SYSTEM_PROMPT = """You are an expert analyst reviewing AI chatbot (LLM) responses about U.S. graduate data science programs, specifically assessing how well these AI systems represent the CU Boulder MS Data Science program.

Each response was generated by an LLM in answer to a prospective student's question. You receive the accumulated analysis from previous entries and ONE new entry to incorporate.

Your tasks:
1. Extract URLs/domains explicitly referenced in the new response — add new ones, increment frequency of existing ones.
2. Identify recurring themes across all responses seen so far — add new themes, increment frequency of recurring ones.
3. Classify improvements needed for CU Boulder's representation:
   - P1 = critical issues that actively harm visibility or introduce inaccuracies
   - P2 = significant content gaps that weaken the program's standing
   - P3 = minor polish, tone, or completeness improvements
4. Record positive mentions of CU Boulder (good_feedback) and negative/missing info (bad_feedback), incrementing frequency when the same point recurs.
5. Surface non-obvious insights that a program marketing team would care about.

Rules:
- Deduplicate aggressively: merge items that mean the same thing, increment their frequency instead of adding duplicates.
- Sort each list by frequency descending.
- Return ONLY valid JSON matching the schema. No prose, no markdown fences, no explanations outside the JSON."""


# ── Ollama helpers ─────────────────────────────────────────────────────────────

def detect_model(preferred: str) -> str:
    """Return the preferred model if available, else the best alternative."""
    try:
        r = requests.get(f"{OLLAMA_BASE}/api/tags", timeout=8)
        r.raise_for_status()
        available = [m["name"].split(":")[0] for m in r.json().get("models", [])]
        if not available:
            print("✗  No models found in Ollama. Pull one first, e.g.:\n   ollama pull llama3.2")
            sys.exit(1)
        pref_base = preferred.split(":")[0]
        if pref_base in available:
            return preferred
        # Fallback preference order
        for fallback in ["llama3.2", "llama3.1", "llama3", "mistral", "qwen2.5", "phi3"]:
            if fallback in available:
                print(f"⚠  '{preferred}' not found. Using '{fallback}' instead.")
                print(f"   Available: {', '.join(available)}")
                return fallback
        chosen = available[0]
        print(f"⚠  '{preferred}' not found. Using '{chosen}'. Available: {', '.join(available)}")
        return chosen
    except requests.exceptions.ConnectionError:
        print("✗  Cannot reach Ollama at http://localhost:11434")
        print("   Make sure it's running:  ollama serve")
        sys.exit(1)


def call_ollama(model: str, prompt: str) -> str:
    payload = {
        "model": model,
        "prompt": prompt,
        "system": SYSTEM_PROMPT,
        "format": "json",
        "stream": False,
        "options": {"temperature": 0.15, "num_predict": 6000},
    }
    r = requests.post(f"{OLLAMA_BASE}/api/generate", json=payload, timeout=TIMEOUT_S)
    r.raise_for_status()
    return r.json()["response"]


def parse_json_safe(text: str) -> dict | None:
    """Try to extract a JSON object from potentially noisy model output."""
    text = text.strip()
    # Direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Find the outermost { ... }
    start = text.find("{")
    end   = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            pass
    return None


# ── Merge helpers ──────────────────────────────────────────────────────────────

def _key(text: str, length: int = 70) -> str:
    """Normalised key for deduplication."""
    return re.sub(r"\s+", " ", text.lower().strip())[:length]


def merge_list(existing: list, incoming: list, key_field: str) -> list:
    """Merge two lists of dicts, deduplicating by key_field, summing frequency."""
    merged: dict[str, dict] = {_key(item[key_field]): dict(item) for item in existing}
    for item in incoming:
        k = _key(item.get(key_field, ""))
        if not k:
            continue
        if k in merged:
            merged[k]["frequency"] = merged[k].get("frequency", 1) + max(
                0, item.get("frequency", 1) - 1
            )
            # Keep the richer description field
            for field in ("description", "context", "rationale", "category"):
                if field in item and len(str(item[field])) > len(str(merged[k].get(field, ""))):
                    merged[k][field] = item[field]
        else:
            merged[k] = dict(item)
    return sorted(merged.values(), key=lambda x: x.get("frequency", 1), reverse=True)


def merge_improvements(existing: dict, incoming: dict) -> dict:
    result = {}
    for priority in ("P1", "P2", "P3"):
        curr = {_key(i["issue"]): dict(i) for i in existing.get(priority, [])}
        for item in incoming.get(priority, []):
            k = _key(item.get("issue", ""))
            if k and k not in curr:
                curr[k] = dict(item)
        result[priority] = list(curr.values())
    return result


def merge_insights(existing: list, incoming: list) -> list:
    merged: dict[str, dict] = {_key(i["insight"]): dict(i) for i in existing}
    for item in incoming:
        k = _key(item.get("insight", ""))
        if k and k not in merged:
            merged[k] = dict(item)
    # Sort by importance
    order = {"high": 0, "medium": 1, "low": 2}
    return sorted(merged.values(), key=lambda x: order.get(x.get("importance", "low"), 2))


def merge_analysis(state: dict, update: dict) -> dict:
    if not update:
        return state
    return {
        "sites":         merge_list(state.get("sites", []),         update.get("sites", []),         "url"),
        "themes":        merge_list(state.get("themes", []),        update.get("themes", []),        "theme"),
        "improvements":  merge_improvements(state.get("improvements", {"P1":[],"P2":[],"P3":[]}), update.get("improvements", {})),
        "good_feedback": merge_list(state.get("good_feedback", []), update.get("good_feedback", []), "point"),
        "bad_feedback":  merge_list(state.get("bad_feedback", []),  update.get("bad_feedback", []),  "point"),
        "insights":      merge_insights(state.get("insights", []),  update.get("insights", [])),
        "processed_ids": list(set(
            state.get("processed_ids", []) + [int(i) for i in update.get("processed_ids", []) if str(i).isdigit()]
        )),
        "entry_count":   update.get("entry_count", state.get("entry_count", 0)),
    }


# ── Persistence ────────────────────────────────────────────────────────────────

def load_state(fresh: bool) -> dict:
    state_file = OUT / "analysis_state.json"
    if not fresh and state_file.exists():
        with open(state_file) as f:
            state = json.load(f)
        print(f"  Resuming from existing analysis ({state.get('entry_count', 0)} entries processed)")
        return state
    import copy
    return copy.deepcopy(EMPTY_ANALYSIS)


def save_state(state: dict) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    # Master state file
    with open(OUT / "analysis_state.json", "w") as f:
        json.dump(state, f, indent=2)
    # Individual output files
    with open(OUT / "sites.json", "w") as f:
        json.dump(state["sites"], f, indent=2)
    with open(OUT / "themes.json", "w") as f:
        json.dump(state["themes"], f, indent=2)
    with open(OUT / "improvements.json", "w") as f:
        json.dump(state["improvements"], f, indent=2)
    with open(OUT / "good_feedback.json", "w") as f:
        json.dump(state["good_feedback"], f, indent=2)
    with open(OUT / "bad_feedback.json", "w") as f:
        json.dump(state["bad_feedback"], f, indent=2)
    with open(OUT / "insights.json", "w") as f:
        json.dump(state["insights"], f, indent=2)


# ── Word cloud ─────────────────────────────────────────────────────────────────

def build_word_freq(entries: list) -> dict:
    counter: Counter = Counter()
    for e in entries:
        text = e.get("response", "")
        words = re.findall(r"\b[a-z]{3,}\b", text.lower())
        counter.update(w for w in words if w not in STOPWORDS)
    return dict(counter.most_common(300))


def cu_gold_color(*args, **kwargs) -> str:
    """Colour function that blends CU Boulder gold (#CFB87C) with dark tones."""
    import random
    shades = ["#CFB87C", "#B89A50", "#9A7C3C", "#7A5C28", "#1a1a1a", "#3d3020"]
    return random.choice(shades)


def generate_wordcloud(freq: dict, output_path: Path) -> None:
    if not HAS_WC:
        print("⚠  wordcloud/matplotlib not installed — skipping.")
        print("   Run:  pip install wordcloud matplotlib")
        return
    if not freq:
        print("⚠  No word frequencies to plot.")
        return

    wc = WordCloud(
        width=1800,
        height=950,
        background_color="white",
        color_func=cu_gold_color,
        max_words=150,
        min_font_size=10,
        prefer_horizontal=0.80,
        collocations=False,
    ).generate_from_frequencies(freq)

    fig, ax = plt.subplots(figsize=(18, 9.5), dpi=100)
    ax.imshow(wc, interpolation="bilinear")
    ax.axis("off")
    fig.suptitle(
        "LLM Audit — Most Recurring Terms Across All Responses",
        fontsize=18, fontweight="bold", color="#1a1a1a", y=0.98,
    )
    plt.tight_layout(pad=0.5)
    plt.savefig(output_path, bbox_inches="tight", dpi=150, facecolor="white")
    plt.close()
    print(f"  ✓  Word cloud → {output_path.name}")


# ── Main ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Analyze LLM audit responses with Ollama")
    p.add_argument("--model",         default=DEFAULT_MODEL, help=f"Ollama model (default: {DEFAULT_MODEL})")
    p.add_argument("--fresh",         action="store_true",   help="Wipe previous analysis and start over")
    p.add_argument("--skip-wordcloud",action="store_true",   help="Skip word cloud generation")
    return p.parse_args()


def build_prompt(entry: dict, state: dict, entry_num: int, total: int) -> str:
    profile = entry.get("profile", "?")
    scores  = entry.get("scores", {})
    resp    = entry.get("response", "").strip()
    if len(resp) > MAX_RESP_CHARS:
        resp = resp[:MAX_RESP_CHARS] + f"\n\n[... response truncated at {MAX_RESP_CHARS} chars ...]"

    # Trim the context state to top items only (saves tokens)
    ctx = {
        "sites":         state.get("sites",        [])[:20],
        "themes":        state.get("themes",       [])[:20],
        "improvements":  {
            "P1": state.get("improvements", {}).get("P1", [])[:10],
            "P2": state.get("improvements", {}).get("P2", [])[:10],
            "P3": state.get("improvements", {}).get("P3", [])[:10],
        },
        "good_feedback": state.get("good_feedback",[])[:15],
        "bad_feedback":  state.get("bad_feedback", [])[:15],
        "insights":      state.get("insights",     [])[:12],
        "processed_ids": state.get("processed_ids",[]),
        "entry_count":   state.get("entry_count",   0),
    }

    return f"""ACCUMULATED ANALYSIS SO FAR ({state.get("entry_count", 0)} of {total} entries processed):
{json.dumps(ctx, indent=2)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NEW ENTRY [{entry_num}/{total}]:
  LLM:         {entry.get("llm", "?")}
  Profile:     {profile} — {PROFILE_LABELS.get(profile, "?")}
  Query type:  {entry.get("qtype", "?")}
  Scores:      Visibility={scores.get("D1","?")}  Accuracy={scores.get("D2","?")}  Completeness={scores.get("D3","?")}  Relevance={scores.get("D4","?")}  Sentiment={scores.get("D5","?")}
  Total score: {entry.get("total", "?")}/15

RESPONSE TEXT:
{resp}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return the COMPLETE UPDATED analysis as JSON matching this schema:
{SCHEMA}

IMPORTANT:
- processed_ids must include all IDs from before PLUS {entry.get("id")}
- entry_count must be {state.get("entry_count", 0) + 1}
- Merge/deduplicate, do NOT duplicate existing items — increment their frequency instead
"""


def main() -> None:
    args = parse_args()

    bar = "═" * 62
    print(f"\n{bar}")
    print("  LLM Audit Response Analysis Agent")
    print(bar)

    # Verify Ollama
    model = detect_model(args.model)
    print(f"  Model : {model}")

    # Load entries
    if not ENTRIES.exists():
        print(f"✗  {ENTRIES} not found.")
        sys.exit(1)
    with open(ENTRIES) as f:
        raw = json.load(f)
    entries = [e for e in raw.get("entries", []) if e.get("response", "").strip()]
    if not entries:
        print("✗  No entries with response text found.")
        sys.exit(1)
    print(f"  Entries with responses: {len(entries)}")

    # Prepare output dir
    OUT.mkdir(parents=True, exist_ok=True)

    # Load or initialise state
    state = load_state(args.fresh)

    # ── Process each entry ─────────────────────────────────────
    errors = 0
    for i, entry in enumerate(entries, 1):
        entry_id = entry.get("id")
        already  = entry_id in state.get("processed_ids", [])

        profile = entry.get("profile", "?")
        llm     = entry.get("llm",     "?")
        qtype   = entry.get("qtype",   "?")
        total_s = entry.get("total",   "?")
        r_len   = len(entry.get("response", ""))

        tag = "skip" if already else "proc"
        print(f"\n  [{i:02d}/{len(entries)}] {llm:<12} P={profile}  {qtype:<16}  {total_s}/15  {r_len:>6} chars  [{tag}]")

        if already:
            continue

        prompt = build_prompt(entry, state, i, len(entries))
        t0 = time.time()
        try:
            raw_resp = call_ollama(model, prompt)
            elapsed  = time.time() - t0
            parsed   = parse_json_safe(raw_resp)
            if parsed:
                # Guarantee processed_ids and entry_count are correct
                parsed.setdefault("processed_ids", [])
                if entry_id not in parsed["processed_ids"]:
                    parsed["processed_ids"].append(entry_id)
                parsed["entry_count"] = i

                state = merge_analysis(state, parsed)
                save_state(state)
                n_sites    = len(state["sites"])
                n_themes   = len(state["themes"])
                n_p1       = len(state["improvements"]["P1"])
                print(f"         ✓  {elapsed:.0f}s  →  sites={n_sites}  themes={n_themes}  P1={n_p1}")
            else:
                errors += 1
                print(f"         ⚠  Could not parse JSON from model (took {time.time()-t0:.0f}s)")
                print(f"            First 200 chars: {raw_resp[:200]!r}")
                # Still mark as attempted so we don't loop forever on bad entries
                state.setdefault("processed_ids", []).append(entry_id)
                state["entry_count"] = i
                save_state(state)

        except requests.exceptions.Timeout:
            errors += 1
            print(f"         ✗  Ollama timed out after {TIMEOUT_S}s — skipping entry")
            state.setdefault("processed_ids", []).append(entry_id)
            save_state(state)
        except Exception as exc:
            errors += 1
            print(f"         ✗  Error: {exc}")
            state.setdefault("processed_ids", []).append(entry_id)
            save_state(state)

    # ── Word frequencies (Python-native, not via Ollama) ───────
    print(f"\n{bar}")
    print("  Building word frequencies from raw response text…")
    word_freq = build_word_freq(entries)
    with open(OUT / "word_frequencies.json", "w") as f:
        json.dump(word_freq, f, indent=2)
    print(f"  ✓  {len(word_freq)} unique terms → word_frequencies.json")

    # ── Word cloud ─────────────────────────────────────────────
    if not args.skip_wordcloud:
        print("  Generating word cloud…")
        generate_wordcloud(word_freq, OUT / "wordcloud.png")

    # ── Summary printout ───────────────────────────────────────
    impr = state.get("improvements", {})
    print(f"""
{bar}
  Analysis complete
{bar}
  Output folder : {OUT}/
  ├─ analysis_state.json    master state (resumable)
  ├─ sites.json             {len(state.get("sites", []))} sources referenced
  ├─ themes.json            {len(state.get("themes", []))} recurring themes
  ├─ improvements.json      P1={len(impr.get("P1",[]))}  P2={len(impr.get("P2",[]))}  P3={len(impr.get("P3",[]))}
  ├─ good_feedback.json     {len(state.get("good_feedback", []))} positive points
  ├─ bad_feedback.json      {len(state.get("bad_feedback", []))} negative / missing points
  ├─ insights.json          {len(state.get("insights", []))} insights
  ├─ word_frequencies.json  {len(word_freq)} terms
  └─ wordcloud.png{"         ✓" if (not args.skip_wordcloud and HAS_WC) else "         (skipped)"}

  Entries processed : {state.get("entry_count", 0)} / {len(entries)}
  Errors            : {errors}
{bar}
""")


if __name__ == "__main__":
    main()
